apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  values:
    defaultSettings.defaultBackupBlockSize: 16
    defaultBackupStore:
      backupTarget: "s3://k3s-longhorn@auto/longhorn/"
      backupTargetCredentialSecret: "longhorn-r2-backups"
      pollInterval: 300
    persistence:
      recurringJobSelector:
        enable: true
        jobList: >-
          [{"name":"default","isGroup":true}]
