apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  # PATCH-ONLY within v1.33.x
  channel: https://update.k3s.io/v1-release/channels/v1.33
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  prepare:
    image: rancher/k3s-upgrade
    args:
      - prepare
      - k3s-server
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  # PATCH-ONLY within v1.33.x
  channel: https://update.k3s.io/v1-release/channels/v1.33
