apiVersion: apps/v1
kind: Deployment
metadata:
  name: film
  namespace: eriktest
  labels:
    app: film
spec:
  replicas: 1
  selector:
    matchLabels:
      app: film
  template:
    metadata:
      labels:
        app: film
    spec:
      nodeName: main
      containers:
        - name: film
          image: itzg/minecraft-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: "1.21"
            - name: TYPE
              value: "NEOFORGE"
            - name: ENABLE_COMMAND_BLOCK
              value: "TRUE"
            - name: CREATE_CONSOLE_IN_PIPE
              value: "true"
            - name: MODS
              value: |-
                chunky
                infinity-tnt
                lucky-tnt-lib
                lucky-tnt-mod
                security-craft
                tnt-breaks-bedrock
            - name: OPS
              value: |-
                BachErik_
                BachCam
          volumeMounts:
            - name: film
              mountPath: /data
      volumes:
        - name: film
          persistentVolumeClaim:
            claimName: film
