apiVersion: apps/v1
kind: Deployment
metadata:
  name: film
  namespace: eriktest
  labels:
    app: film
spec:
  replicas: 1
  selector:
    matchLabels:
      app: film
  template:
    metadata:
      labels:
        app: film
    spec:
      nodeName: main
      containers:
        - name: film
          image: itzg/minecraft-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: "1.21"
            - name: TYPE
              value: "NEOFORGE"
            - name: ENABLE_COMMAND_BLOCK
              value: "TRUE"
            - name: CREATE_CONSOLE_IN_PIPE
              value: "true"
            - name: MODRINTH_PROJECTS
              value: |-
                chunky
                collective:ao7rZsss
                infinity-tnt
                lucky-tnt-lib:ezvk3Z4l
                lucky-tnt-mod:poxpbC0y
                security-craft:9aseGMM0
                tnt-breaks-bedrock
                worldedit:WTAFvuRx
            - name: OPS
              value: |-
                BachErik_
                BachCam
            - name: WORLD
              value: https://workupload.com/start/KjbrA2Z3e5x
          volumeMounts:
            - name: film
              mountPath: /data
      volumes:
        - name: film
          persistentVolumeClaim:
            claimName: film
