apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router
  namespace: eriktest
spec:
  interval: 5m
  chart:
    spec:
      chart: mc-router
      version: "1.4.1"
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: eriktest