apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minecraft-server-charts
  namespace: eriktest
spec:
  interval: 1h
  url: https://itzg.github.io/minecraft-server-charts/
