apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc1
  namespace: eriktest
  labels:
    app: mc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc1
  template:
    metadata:
      labels:
        app: mc1
    spec:
      containers:
        - name: mc1
          image: itzg/minecraft-server:java8
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: TYPE
              value: "CUSTOM"
            - name: CUSTOM_SERVER
              value: "https://file.bacherik.de/minecraft/versions/spigot-1.8.jar"
            - name: FORCE_GAMEMODE
              value: "TRUE"
            - name: MODE
              value: "CREATIVE"
            - name: ENABLE_COMMAND_BLOCK
              value: "TRUE"
            - name: "FORCE_REDOWNLOAD"
              value: "TRUE"
            - name: CREATE_CONSOLE_IN_PIPE
              value: "true"
            - name: OPS
              value: |-
                BachErik_
          volumeMounts:
            - name: mc1
              mountPath: /data
      volumes:
        - name: mc1
          persistentVolumeClaim:
            claimName: mc1
