apiVersion: v1
kind: Service
metadata:
  name: mc2
  namespace: eriktest
  annotations:
    mc-router.itzg.me/externalServerName: "mc2.bacherik.de"
    external-dns.alpha.kubernetes.io/hostname: "mc2.bacherik.de"
spec:
  selector:
    app: mc2
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP