apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc2
  namespace: eriktest
  labels:
    app: mc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc2
  template:
    metadata:
      labels:
        app: mc2
    spec:
      containers:
        - name: mc2
          image: itzg/minecraft-server:latest
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
          volumeMounts:
            - name: mc2
              mountPath: /data
      volumes:
        - name: mc2
          persistentVolumeClaim:
            claimName: mc2