apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc2
  namespace: eriktest
  labels:
    app: mc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc2
  template:
    metadata:
      labels:
        app: mc2
    spec:
      containers:
        - name: mc2
          image: itzg/minecraft-server:java8
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: TYPE
              value: "CUSTOM"
            - name: CUSTOM_SERVER
              value: "https://file.bacherik.de/minecraft/versions/spigot-1.10.2.jar"
            - name: FORCE_GAMEMODE
              value: "TRUE"
            - name: MODE
              value: "CREATIVE"
            - name: ENABLE_COMMAND_BLOCK
              value: "TRUE"
          volumeMounts:
            - name: mc2
              mountPath: /data
      volumes:
        - name: mc2
          persistentVolumeClaim:
            claimName: mc2