apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc3
  namespace: eriktest
  labels:
    app: mc3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc3
  template:
    metadata:
      labels:
        app: mc3
    spec:
      containers:
        - name: mc3
          image: itzg/minecraft-server:latest
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: "1.21.5"
            - name: TYPE
              value: "PAPER"
            - name: MODE
              value: "CREATIVE"
            - name: ENABLE_COMMAND_BLOCK
              value: "TRUE"
            - name: CREATE_CONSOLE_IN_PIPE
              value: "true"
          volumeMounts:
            - name: mc3
              mountPath: /data
      volumes:
        - name: mc3
          persistentVolumeClaim:
            claimName: mc3