apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    # For configuration options and examples, please see:
    # https://gethomepage.dev/latest/configs/settings

    providers:
      openweathermap: openweathermapapikey
      weatherapi: weatherapiapikey
    title: The Home of Erik
    background:
      image: https://static-cdn.jtvnw.net/jtv_user_pictures/4d590367-c265-4d2e-ab4b-d7ddae003631-profile_banner-480.png
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 50 # 0-100
    cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur
    favicon: https://avatars.githubusercontent.com/u/75324423?v=4
    description: The homepage of BachErik
    theme: dark # or light
    color: slate
    headerStyle: clean
  custom.css: ""
  custom.js: |
    document.addEventListener('DOMContentLoaded', function() {
      console.log("Custom JS is loaded");
    
      var bookmarks = document.querySelectorAll('li.bookmark[data-name="Mastodon"]');
      
      bookmarks.forEach(function(bookmark) {
        var link = bookmark.querySelector('a');
        
        if (link) {
          link.setAttribute('rel', 'me');
          console.log("rel='me' set for", link.href);
        }
      });
    });

  bookmarks.yaml: |
    # For configuration options and examples, please see:
    # https://gethomepage.dev/latest/configs/bookmarks

    - ME-System:
        - 1.17:
            - abbr: 17
              href: https://file.bacherik.de/minecraft/maps/ME-System/ME-System_1.17.zip
              icon: minecraft.svg
              description: Download the Minecraft ME-System for Minecraft version 1.17
        - 1.18 / 1.19:
            - abbr: 18
              href: https://file.bacherik.de/minecraft/maps/ME-System/ME-System_1.18-1.19.zip
              icon: minecraft.svg
              description: Download the Minecraft ME-System for Minecraft versions 1.18 and 1.19
        - 1.20.x:
            - abbr: 20.x
              href: https://file.bacherik.de/minecraft/maps/ME-System/ME-System_1.20.x.zip
              icon: minecraft.svg
              description: Download the Minecraft ME-System for Minecraft version 1.20.x

    - GitHub:
        - BachErik:
            - abbr: BE
              href: https://github.com/BachErik
              icon: github-light.png
              description: Here you can see how bad I actually am at programming.
        - BachErik-Team:
            - abbr: BET
              href: https://github.com/BachErik-Team
              icon: github-light.png
              description: Just some organization.
        - SecuritySchool:
            - abbr: S
              href: https://github.com/SecSchool
              icon: github-light.png
              description: A platform, among others, created by Niklas, which is quite something.

    - Social:
        - Instagram:
            - abbr: I
              href: https://www.instagram.com/BachErik_live/
              icon: instagram.svg
              description: My irregular Instagram account.
        - Twitter / X:
            - abbr: X
              href: https://twitter.com/BachErik_live
              icon: twitter.svg
              description: My opinions are unimportant.
        - Discord:
            - abbr: DC
              href: https://discord.gg/9K8hVWcjFW
              icon: discord.svg
              description: My community Discord server.
        - Mastodon:
            - abbr: M
              href: https://mastodon.social/@BachErik
              icon: mastodon.svg
              description: In case Twitter dies.
        - E-Mail:
            - abbr: E
              href: mailto:info@bacherik.de
              icon: mdi-email-#F2FBFB
              description: The classic way.
    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/@bacherik_live
              icon: youtube.svg
              description: Videos every few years.
        - Twitch:
            - abbr: T
              href: https://twitch.tv/bacherik_live
              icon: twitch.svg
              description: One can always dream...
  services.yaml: |
    # For configuration options and examples, please see:
    # https://gethomepage.dev/latest/configs/services

    - SecSchool:
        - GitHub:
            href: https://github.com/SecSchool
            icon: github-light.png
            description: A platform, among others, created by Niklas, which is quite something.
        - Discord:
            href: https://discord.gg/2bWxKHn8Yd
            icon: discord.svg
            description: The Security School Discord server.
        - Website:
            href: https://secschool.net/
            icon: https://avatars.githubusercontent.com/u/138791564?s=200&v=4
            description: (Not finished yet.)
            ping: secschool.net
        - Twitch:
            href: https://twitch.tv/secscool
            icon: twitch.svg
    - Uptime:
        - Status page:
            href: https://status.bacherik.de
            icon: https://avatars.githubusercontent.com/u/75324423?v=4
        - Main server:
            description: My main server reachable at main.bacherik.de
            widget:
                type: uptimerobot
                url: https://api.uptimerobot.com
                key: m796718516-ca9cd9d6ec77a419849e369e
                hideErrors: true
        - Sync server:
            description: This server hosts this site. It is reachable at sync.bacherik.de
            widget:
                type: uptimerobot
                url: https://api.uptimerobot.com
                key: m796868779-af16b0edc81af7ebafa9f2a5
                hideErrors: true
        - bacherik.de:
            description: My main website domain.
            widget:
                type: uptimerobot
                url: https://api.uptimerobot.com
                key: m794087503-81ed24efc6b06dad863640ca
                hideErrors: true
    - Minecraft Servers:
        - Eulengames:
            description: Eulengames network.
            widget:
                type: minecraft
                url: udp://eulengames.net:25565
                players: True
                version: True
                status: True
        - TheJoCraft:
            description: TheJoCraft network.
            href: https://thejocraft.net
            icon: https://avatars.githubusercontent.com/u/122056285?s=200&v=4
            widget:
                type: minecraft
                url: udp://thejocraft.net:25565
                players: True
                version: True
                status: True
        - Hypixel:
            description: Everyone knows it.
            href: https://hypixel.net
            icon: https://hypixel.net/styles/hypixel-v2/images/hypixel-512px.png
            widget:
                type: minecraft
                url: udp://mc.hypixel.net:25565
                players: True
                version: True
                status: True
  widgets.yaml: |
    # For configuration options and examples, please see:
    # https://gethomepage.dev/latest/configs/service-widgets

    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - resources:
        cpu: false
        memory: false
        disk: false

    - datetime:
        # 06.05.24, 17:50:40 MESZ
        locale: en
        format:
            dateStyle: short
            timeStyle: long
    - logo:
        icon: https://avatars.githubusercontent.com/u/75324423?v=4
  docker.yaml: ""
