apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gethomepage
resources:
  - namespace.yaml
  - service-account.yaml
  - secret.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - config-map.yaml