apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reposilite
  namespace: reposilite
spec:
  interval: 5m
  chart:
    spec:
      chart: reposilite
      version: "1.2.21"
      sourceRef:
        kind: HelmRepository
        name: reposilite
        namespace: reposilite