apiVersion: v1
kind: Namespace
metadata:
  name: redirect
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: redirect
  namespace: redirect
spec:
  interval: 1m
  url: https://bacherik.github.io/k8s-redirects/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redirect
  namespace: redirect
spec:
  interval: 1m
  chart:
    spec:
      chart: k8s-redirects
      version: "0.2.21"
      sourceRef:
        kind: HelmRepository
        name: redirect
        namespace: redirect
      interval: 12h
  values:
    redirects:
      - name: bluesky
        host: bluesky.lyre.works
        regex: "^https?://bluesky\\.lyre\\.works(?:/(.*))?"
        replacement: "https://bsky.app/profile/lyre.works/"
        permanent: true
        image: traefik/whoami
        port: 80
        issuer: letsencrypt
      - name: bsky
        host: bsky.lyre.works
        regex: "^https?://bsky\\.lyre\\.works(?:/(.*))?"
        replacement: "https://bsky.app/profile/lyre.works/"
        permanent: true
        image: traefik/whoami
        port: 80
        issuer: letsencrypt
      - name: github
        host: github.lyre.works
        regex: "^https?://github\\.lyre\\.works(?:/(.*))?"
        replacement: "https://github.com/LyreWorks/${1}"
        permanent: true
        image: traefik/whoami
        port: 80
        issuer: letsencrypt
      - name: gh
        host: gh.lyre.works
        regex: "^https?://gh\\.lyre\\.works(?:/(.*))?"
        replacement: "https://github.com/LyreWorks/${1}"
        permanent: true
        image: traefik/whoami
        port: 80
        issuer: letsencrypt
      - name: test
        host: test.bacherik.de
        regex: "^https?://test\\.bacherik\\.de(?:/(.*))?"
        replacement: "https://example.com/${1}"
        permanent: true
        image: traefik/whoami
        port: 80
        issuer: letsencrypt
        tlsSecretName: "test-tls"