apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-bluesky-lyre
  namespace: default
spec:
  redirectRegex:
    regex: "^https?://bluesky\\.lyre\\.works(?:/(.*))?"
    replacement: "https://bsky.app/profile/lyre.works/${1}"
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-bluesky-lyre
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostename: bluesky.lyre.works
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`bluesky.lyre.works`)
      kind: Rule
      middlewares:
        - name: redirect-bluesky-lyre
      services:
        - name: noop@internal
          kind: TraefikService