apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-platform
  namespace: databases
spec:
  managed:
    roles:
      - name: keycloak
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: keycloak-db-creds