apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weblate
  namespace: weblate
spec:
  interval: 5m
  chart:
    spec:
      chart: weblate
      version: "0.5.21"
      sourceRef:
        kind: HelmRepository
        name: weblate
        namespace: weblate