apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      # Init-Container wartet, bis Postgres erreichbar ist
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        command: ['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo "Waiting for postgres..."; sleep 2; done;']
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:v2.8.0
        env:
        - name: ALLOW_SIGNUP
          value: "false"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Anchorage"
        - name: BASE_URL
          value: "https://mealie.yourdomain.com"
        - name: DB_ENGINE
          value: "postgres"
        - name: POSTGRES_USER
          value: "mealie"
        - name: POSTGRES_PASSWORD
          value: "mealie"
        - name: POSTGRES_SERVER
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "mealie"
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: "1000M"
        volumeMounts:
        - name: mealie-data
          mountPath: /app/data/
      volumes:
      - name: mealie-data
        persistentVolumeClaim:
          claimName: mealie-data