apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
  - namespace.yaml
  - pvc-data.yaml
  - pvc-pgdata.yaml
  - deployment-postgres.yaml
  - service-postgres.yaml
  - deployment-mealie.yaml
  - service-mealie.yaml
  
  - service.yaml
  - ingress.yaml