apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 5m
  chart:
    spec:
      chart: ollama
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
        namespace: ollama
  values:
    ollama.models:
      pull:
        - llama2
        - mistral
        - deepseek-r1
      run:
        - llama2
        - deepseek-r1
    persistentVolume:
      # -- Enable persistence using PVC
      enabled: true