apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "1.13.4"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: n8n
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      hosts:
        - host: n8n.bacherik.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: n8n-tls
          hosts: 
            - n8n.bacherik.de