apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-rtmp-conf
  namespace: rtmp
data:
  nginx.conf: |
    worker_processes  auto;
    events { worker_connections  1024; }

    rtmp {
      server {
        listen 1935;
        chunk_size 4096;

        application live {
          live on;
          record off;
          # Für "einfach nur geht": jedem das Publizieren/Abspielen erlauben
          allow publish all;
          allow play all;
        }
      }
    }

    # Minimales http{}-Block, damit nginx glücklich ist (nicht für Stream nötig)
    http {
      server {
        listen 8080;
        location / { return 200 'ok\n'; }
      }
    }
