apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stirlingpdf
  namespace: stirlingpdf
spec:
  interval: 1h
  url: https://stirling-tools.github.io/Stirling-PDF-chart
