apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  values:
    metrics:
      prometheus:
        service:
          enabled: true
          addEntryPointsLabels: true
          addRoutersLabels: true
          addServicesLabels: true
          buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0
        serviceMonitor:
          enabled: true
          namespace: kube-prometheus-stack
          additionalLabels:
            release: kube-prometheus-stack