apiVersion: v1
data:
    config-yaml: ENC[AES256_GCM,data:7YnK06jf3wbqTJ+rWjrFWkhlft4S4zmZEqeiboUB/oNbWVdgjPdDQ1qmRo9o+xFgGP3UnrKW9SiRBh6FIAriESCe3LieCV/YNenyBFFzz/eyYAHEch+HaWPfW7sdhICEiAIHsQ5IBBw076KliOgV6X9UsVK/M6KM7KSKfxT9GOxwtTGXBLQKIi0wQd7fSaZTZDEeQ90J3oDCBB4ExJDrdd9odqc2RpX9frgbnw4jenlkJZMzzWadJtCjo1QbEtDRMWhTRznzaIGB8vp2uhrxXf/YhfIjA2VDj5HTYMqhx3r65GLC06GrOwOlTwIzMsn/0xzr6H6aejqbE9r6zrXyfmya8EVV7mQuIdkz8T59BmaNblDxPuuPXmLCyEyr3PhiIsE2la70uaoy0jxUITaUzeZtIUC8adTVMHv81Rk7g7nff3MW/7PLFDLRqmxRqi8NfPnRCOi/+VHFF+/jJ/2b01N0yJLc6BWvI1tMdgvwe6mLTHeetpLjwDMoHW4uKXAvpZQP0g0mr7XSc9cdPoyIuuaypMZXO/un5GKvkP/IqqvPlC70JN+QSi3Dg7tnJ/otQnNQbyFA4njQx0m7,iv:PeQbl8+Uy7gfZxTXzIoFt1KqiWnyU01eIh4lf9/uFWA=,tag:3IIv2/I1tv8EkPgEytwIqQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: zitadel-db-credentials
    namespace: zitadel
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUlVDNlhxUFB1c0xoN0NK
            SENGQlVPK3lPOUJRaXlOdGh0eUhvemRWT2pJCkhRakt2RWMwTWFWNkhuNG5qc3ZQ
            S1owWXU0ZTZBZS9HZ0hXRDcxWUlUVGMKLS0tIDRMbUJJREU3L2hVZk9sNDRmSkNY
            d3R5alNmNHFPSjl6cjl3Zk54anpueVUKFZKbG6tU1dMTNnQjIiB5PdR1KqGFD9/q
            JcfkYh0Nqrra9wVUwWKQe0QMCqIy3A+8g4zKD/GXv08E0zs307/5kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T19:13:06Z"
    mac: ENC[AES256_GCM,data:GxDlZoQ9yNiGTqQsLBl94RLevcPoSUwUcID/klMNwBnlCZsi8c6qWKTc5qUKEVk65tIuNUb4HQL/QobIChx1Le6wRxC4CpNKgc7/JzJ08I65stOH461BYg9H+NC/fVR67KqtllMKuXlf7RpKXzwNIE+r29h0u+Esk1ODGnjdYx0=,iv:OLE7u3l0BSzTvQuwVW8s+kEG+M/HZeEhP4eB5kiaaNQ=,tag:/Fe9ERy9aaEzuLzmwSUByg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4