apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 1h
  url: https://charts.zitadel.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: zitadel
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
