apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 5m
  chart:
    spec:
      chart: zitadel
      version: "9.23.0"
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: zitadel
  values:
    replicaCount: 2

    zitadel:
      masterkeySecretName: zitadel-masterkey
      configSecretName: zitadel-db-credentials
      configmapConfig:
        ExternalDomain: "zitadel.bacherik.de"
        ExternalSecure: true
        ExternalPort: 443
        TLS:
          Enabled: false
        Database:
          Postgres:
            Host: "zitadel-db-postgresql"
            Port: 5432
            Database: "zitadel"
            User:
              Username: "zitadel"
              SSL:
                Mode: disable
            Admin:
              Username: "postgres"
              SSL:
                Mode: disable
        FirstInstance:
          Org:
            Human:
              UserName: "admin"
              FirstName: "Zitadel"
              LastName: "Admin"
              Email: "admin@example.com"
              Password: "YourSecurePassword123!"
              PasswordChangeRequired: true

    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      hosts:
        - host: zitadel.bacherik.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: zitadel-tls
          hosts:
            - zitadel.bacherik.de

    login:
      ingress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
        hosts:
          - host: zitadel.bacherik.de
            paths:
              - path: /ui/v2/login
                pathType: Prefix
        tls:
          - secretName: zitadel-tls
            hosts:
              - zitadel.bacherik.de

    podDisruptionBudget:
      enabled: true
      minAvailable: 1