apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 5m
  chart:
    spec:
      chart: gatus
      version: "1.2.0"
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: gatus
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      tls:
        - secretName: gatus-tls
          hosts:
            - gatus.bacherik.de
      hosts:
        - gatus.bacherik.de