apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 5m
  chart:
    spec:
      chart: gatus
      version: "1.2.0"
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: gatus
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      tls:
        - secretName: status-tls
          hosts:
            - status.bacherik.de
      hosts:
        - status.bacherik.de
    config:
      ui:
        title: "BachErik's status"
        description: "BachErik's stautspage. It show all services related to BachErik and there status."
        header: "BachErik's status"
        logo: https://avatars.githubusercontent.com/u/75324423?v=4
        link: https://status.bacherik.de
      storage:
        type: postgres
        path: "postgres://user:password@postgres-service.gatus.svc.cluster.local:5432/gatus?sslmode=disable"
        caching: true

      connectivity:
        checker:
          target: 1.1.1.1:53
          interval: 60s

      endpoints:
        # HTTP/S-Überprüfungen
        - name: Homepage
          group: "services"
          url: "https://bacherik.de"
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Download Server
          group: "services"
          url: "https://file.bacherik.de"
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Hastebin
          group: "services"
          url: "https://haste.bacherik.de"
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Docs
          group: "services"
          url: "https://docs.bacherik.de"
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Killedby
          group: "services"
          url: "https://killedby.bacherik.de"
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Dashboard
          group: "services"
          url: "https://dashboard.bacherik.de"
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        # Server-Pings via ICMP
        - name: main
          group: "server"
          url: "icmp://85.215.129.175"
          interval: 60s
          conditions:
            - "[CONNECTED] == true"

        - name: sync
          group: "server"
          url: "icmp://85.215.61.227"
          interval: 60s
          conditions:
            - "[CONNECTED] == true"

        - name: fetch
          group: "server"
          url: "icmp://85.215.137.43"
          interval: 60s
          conditions:
            - "[CONNECTED] == true"