apiVersion: v1
kind: Namespace
metadata:
    name: external-dns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNUJzUFMvNEh3dGpFbWVz
            eG5md0Y4UUtOUnJOcHVUbzNkdlNRUVZYdTJzCi9XbDk1cUVGR2NRYUR1aEIrYVdS
            ZEpUYUtQNFlyemQvQ1JYVU83NUhuQzgKLS0tIEd4VkNzVmJFTSt0clZ0aCtrQW54
            K1ZqeVRxWGRFUTByRWxmM0locjZQRkUKrD6CjeaDvjvm8doTWpXszDCimEcI6ByH
            JO7CsZSSo07fkv+tAVlA+T+CQPnqcrxY19xf9TSFWWDx5LoUgpGKXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T16:36:56Z"
    mac: ENC[AES256_GCM,data:YVrWRk96Xag1KyDkT75Hod2yohylMDMo9DB0mSHOzHkchVcmCYfLq5GlSYaFshjOecPvdOk0TJrJwGZYo35XR+fmg2cpMze1k1vMiKBFZ6d2s1qY9sR4mGzxYVqDE6B3dFVW6J9c84hd7bFqcPdsLmepuhEyasyvK84ekXS4nSI=,iv:9NFZ+EN1WorEBPLabVwApmC5X3rb9HyrTjhT9TluwrU=,tag:7fiKaYfv531sPC1vfAEDoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
data:
    apiKeyTest: ENC[AES256_GCM,data:6iQp2+qaCmbGIXYrPKqXKkCRkhrFv9FcI/YlIopzqv68smWR8shLJjXTdvPKCYrcvXIJjZiuEKY=,iv:KjisfhE5ObOu4RkMLkdZcGQDtBHD73/RDO0yCTRpF8A=,tag:zTgKO+/Nw2YIgAJReMP6LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNUJzUFMvNEh3dGpFbWVz
            eG5md0Y4UUtOUnJOcHVUbzNkdlNRUVZYdTJzCi9XbDk1cUVGR2NRYUR1aEIrYVdS
            ZEpUYUtQNFlyemQvQ1JYVU83NUhuQzgKLS0tIEd4VkNzVmJFTSt0clZ0aCtrQW54
            K1ZqeVRxWGRFUTByRWxmM0locjZQRkUKrD6CjeaDvjvm8doTWpXszDCimEcI6ByH
            JO7CsZSSo07fkv+tAVlA+T+CQPnqcrxY19xf9TSFWWDx5LoUgpGKXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T16:36:56Z"
    mac: ENC[AES256_GCM,data:YVrWRk96Xag1KyDkT75Hod2yohylMDMo9DB0mSHOzHkchVcmCYfLq5GlSYaFshjOecPvdOk0TJrJwGZYo35XR+fmg2cpMze1k1vMiKBFZ6d2s1qY9sR4mGzxYVqDE6B3dFVW6J9c84hd7bFqcPdsLmepuhEyasyvK84ekXS4nSI=,iv:9NFZ+EN1WorEBPLabVwApmC5X3rb9HyrTjhT9TluwrU=,tag:7fiKaYfv531sPC1vfAEDoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4