apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
data:
    apiKey: ENC[AES256_GCM,data:muDFaxzWsUDGoF7OASvZ0OAkzWwgK9HQ2QtRabOykkhKKN5xSz3piMM9HEpOFPRYXd7V0KRAlRA=,iv:9SXJxdGaEKJPZW/rYeEFxMn6y+3MIkb+7GVZhnxTxpI=,tag:ssbDjwrDig2OCDJ9O+unWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TUJ6a29GU01CdWZ4bHkv
            dFpJeVU0UGlTU2FwUXJrTitZc2pONmRGT3pNCm5rS0Y0NVkyckRFYzQyeTloTFZs
            NTU0ZXFLQUhwV3ErSTJwOTU2cG9Mdm8KLS0tIDBqVWRxL1RqbzhxSzB1bm4yUitP
            a1lHOUZ1REswU2NYVG8rZkFXeW9TN3cKx6g5r2EBYPsublWgIYESuLphO6MRh546
            RdiVP496E+iHPX0Sj9sCX91bz7wgGi1rwqr1Uvn2DjbaTECHJG0toA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T16:22:19Z"
    mac: ENC[AES256_GCM,data:7QOVIeOA69rxlbhQONYrnwn6YpUDf9qebIvUoD535N8pAbUh23kRTgNK9BgsS29mKWC0rffkKebc8ET5BJJ/2Jj7JmldNn9tGhjTTsBYqnBBQtBkJsDZKA7pjP04ra1W7gmmIxPzlnhyj3axdIEpR5yZ4tLjsmgTcVSMazexIGw=,iv:yEbj9SZFtnbZi8v8rwoWBAjjQbA3bW8mpqlcrM+oB/k=,tag:olHHSnB2cFh8+jyBql5v+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4