apiVersion: v1
kind: Namespace
metadata:
    name: external-dns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYjlJdjBxZTcvNnFDTXg5
            alNIV3NXTDVXeDdkK1JzclcybTkrR01idzFZCnR4TzA1dUNaK3ZKUlpQdUt4bVRB
            Y3RiRk1EOXJFMUVkZm9Ianp1YXZYbTgKLS0tIFp5RFJGM3Z2MHYzYzZWdVhMaGNw
            NGkvTnhKRVlaL0VBUVVtL0hzemIxb0EK65phRFnf1+90YcCJJ/5tLfPFAZmRSjLP
            U4brahAduyU/88WRHcfY7iV2RMlF8shInI+TWiD24D5t3QzJ0GR+WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T16:39:06Z"
    mac: ENC[AES256_GCM,data:XCUNu5g7C/iUO7ZJJxoQb1Vn9jr6LqmKd306UjmxCIqpIepIWDOyr8B31L0Es8Cbjns/fym0yAnt3mkuuh+dL8+V6g2Lblq+7GOohwH4FgMxy/+rua8ZVmiy0/13XgGf//9h3dImG1PXWVCwJ56HN18A+kqJff0JRxChYcG52no=,iv:c3YQ9OQpEGSgQcYT9GVuNoHeechozvlbxqFCNkvhHaE=,tag:Z0CYurmbhBP+KbutJXHRxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
data:
    apiKey: ENC[AES256_GCM,data:7STugCfyGJa4zG/G2zjdEfW6SfuKSH4kC9OQTTTdnC+gTILWfmb9M45sV0q0Bezxz2XGhgLxvDc=,iv:3f8ol5wJxya8chM3eCpzuE0hgTvsRVQ78BTafgaECTM=,tag:lGXN1C2tDDT6hJGLMa6auQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYjlJdjBxZTcvNnFDTXg5
            alNIV3NXTDVXeDdkK1JzclcybTkrR01idzFZCnR4TzA1dUNaK3ZKUlpQdUt4bVRB
            Y3RiRk1EOXJFMUVkZm9Ianp1YXZYbTgKLS0tIFp5RFJGM3Z2MHYzYzZWdVhMaGNw
            NGkvTnhKRVlaL0VBUVVtL0hzemIxb0EK65phRFnf1+90YcCJJ/5tLfPFAZmRSjLP
            U4brahAduyU/88WRHcfY7iV2RMlF8shInI+TWiD24D5t3QzJ0GR+WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T16:39:06Z"
    mac: ENC[AES256_GCM,data:XCUNu5g7C/iUO7ZJJxoQb1Vn9jr6LqmKd306UjmxCIqpIepIWDOyr8B31L0Es8Cbjns/fym0yAnt3mkuuh+dL8+V6g2Lblq+7GOohwH4FgMxy/+rua8ZVmiy0/13XgGf//9h3dImG1PXWVCwJ56HN18A+kqJff0JRxChYcG52no=,iv:c3YQ9OQpEGSgQcYT9GVuNoHeechozvlbxqFCNkvhHaE=,tag:Z0CYurmbhBP+KbutJXHRxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4