apiVersion: v1
kind: Namespace
metadata:
    name: external-dns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMTg2dXpiS25ZKzRHcXNW
            QmZSZjlhbnBydUltREpVL3VGbFZBZmhUdkZrCit0YThIVGxPaHB6NDZqdHlIME5C
            L2hubEIxenZaZmthd2tmU1NNeXdrSTgKLS0tIEdBdWM1QXZoTzNqMTNDTXVsbjdX
            TWtPV0dtL3hyUSt4SElSM0JTM1paMTQKgmrSo3/CzGokWuchqPTHqfLguCs0okWn
            1dpOQO8vLJZZyG32s3IV80HwZLbQj0Fg0Y3iH9LIQ6yyn8w87PnLZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T16:26:14Z"
    mac: ENC[AES256_GCM,data:SMkkp7xB7DKi6HrgM6Q7nUBAm8ywkuxVyEfVEAa4GakD6BTuWL63m/CoMa8t0Axq1e55ikU5aqFp4RDNBwwgW07zWp+ullsvdNiHVtMH/GJ5TuoKs7/ds/dq2HHODiiMYNl07jWETzXguJ0QhjINkucnNvskmx+FNxFD3kAEDII=,iv:+mycFKbTbUROWsyU1UAMZNv5ztITMD8d+nd77JwVLXc=,tag:RUgLfh5TT5NlTBToGBUHYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
data:
    apiKey: ENC[AES256_GCM,data:IRA1JrtSUQkqC+KjQMbKKGpq8uzs1lujA34WTsLciN7wxJxpJEf3Dk3DQtk/Q0KthT0cD+6Gj1g=,iv:unCO9e2CkzeuIe6E20ITqN6WKL0e8FbX60L3siBLgHU=,tag:0T4phDTj9PAwkPAZKvxw/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMTg2dXpiS25ZKzRHcXNW
            QmZSZjlhbnBydUltREpVL3VGbFZBZmhUdkZrCit0YThIVGxPaHB6NDZqdHlIME5C
            L2hubEIxenZaZmthd2tmU1NNeXdrSTgKLS0tIEdBdWM1QXZoTzNqMTNDTXVsbjdX
            TWtPV0dtL3hyUSt4SElSM0JTM1paMTQKgmrSo3/CzGokWuchqPTHqfLguCs0okWn
            1dpOQO8vLJZZyG32s3IV80HwZLbQj0Fg0Y3iH9LIQ6yyn8w87PnLZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T16:26:14Z"
    mac: ENC[AES256_GCM,data:SMkkp7xB7DKi6HrgM6Q7nUBAm8ywkuxVyEfVEAa4GakD6BTuWL63m/CoMa8t0Axq1e55ikU5aqFp4RDNBwwgW07zWp+ullsvdNiHVtMH/GJ5TuoKs7/ds/dq2HHODiiMYNl07jWETzXguJ0QhjINkucnNvskmx+FNxFD3kAEDII=,iv:+mycFKbTbUROWsyU1UAMZNv5ztITMD8d+nd77JwVLXc=,tag:RUgLfh5TT5NlTBToGBUHYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4