apiVersion: v1
kind: Namespace
metadata:
  name: error-pages
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages
  namespace: error-pages
spec:
  replicas: 3
  selector:
    matchLabels:
      app: error-pages
  template:
    metadata:
      labels:
        app: error-pages
    spec:
      containers:
      - name: error-pages
        image: ghcr.io/bacherik/error-pages:latest
---
apiVersion: v1
kind: Service
metadata:
  name: error-pages
  namespace: error-pages
spec:
  selector:
    app: error-pages
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: error-pages
  namespace: error-pages
spec:
  errors:
    status:
      - "400"
      - "404"
      - "500"
      - "501"
      - "503"
      - "505-599"
    query: /{status}.html
    service:
      name: error-pages
      port: 80