apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: switchboard
  namespace: switchboard
spec:
  interval: 24h
  url: oci://ghcr.io/borchero/charts/switchboard
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: switchboard
  namespace: switchboard
spec:
  interval: 30m
  chart:
    spec:
      chart: switchboard
      version: "0.7.1"
      sourceRef:
        kind: HelmRepository
        name: switchboard
        namespace: switchboard
      interval: 12h
  values:
    integrations.externalDNS:
      enabled: true
      targetService.name: traefik
      targetService.namespace: traefik