apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: "6.6.10"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
  values:
    nextcloud.host: nextcloud.bacherik.de
    persistence:
      enabled: true
      nextcloudData.enabled: true
    nextcloud.trustedDomains: nextcloud.bacherik.de
    externalDatabase.enabled: true
    mariadb.enabled: true
    postgresql.enabled: true
    postgresql.primary.persistence.enabled: true
    redis.enabled: true
    cronjob.enabled: true
    hpa: true
