kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: diskube
subjects:
  - kind: ServiceAccount
    name: default
    namespace: diskube
roleRef:
  kind: ClusterRole
  name: diskube
  apiGroup: rbac.authorization.k8s.io
