apiVersion: v1
kind: Secret
metadata:
  name: shlink-secret
  namespace: shlink
type: Opaque
stringData:
  #ENC[AES256_GCM,data:LLZSaD03mzveeUQhbnh+yvVlIlUSrITzdOsqpBTJKY96rJwiOGwVZjOG1g==,iv:KiM+tk8+yWqTUM13bb5CVCOFHJimK7OvFiBI9JpORAI=,tag:m9PlWphkzXEk/vA8kAFsUA==,type:comment]
  DB_PASSWORD: ENC[AES256_GCM,data:bPgSFoQzJ60uIzPGH2h6jhfte2URQejPg+McneCDKMxom2sc,iv:DfH/5Y1JhY3j5rcoLVLi5ZmQef9h2bWiVFwtuhiWrPA=,tag:74Wsmb8SY3y/yxPE1oTKOg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSldpSzJ4T0xhdDNHTFhS
        eEdCQm5nWlBrTStIU2ZwZmpjcEthNTZJTWpnCi9DMGtqV1ZzdDhDNzFXUi9nYUVF
        QUJVQWVYNitnREUwU1kxQXh5VjVIaHMKLS0tIHpZaVRCTDhYRnhTMnZwbUpNSnJV
        WFljNjYvQzR5bjdEbjFKNFN5ZkJ1OFUKJd9jA1TNA1+9iCabpGTIT+1I1xcSit14
        dMZ/iLwQzM5rLT0nZ0zx+7FYJoZjZWfUMFxB1s51SbS6KpZPVzvLOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-21T12:07:08Z"
  mac: ENC[AES256_GCM,data:8vDI50v7jz07vnH6cTpODI+SL31mhyY4qa9keTwh4ucrwxIT/snN+xJmV8pgnbvLq1ybLQ2GVECUSpdkjDGiLS61GVdR7PsO0jW2NADhbhf+ukEvqloYK1zmBWnZNfxSw8vG5CQl7ZbbvEEnDq0U8fr7XG9oxn45OJ3jYz7DBaI=,iv:D1hh+MlqxNYWR6MM8V4gh+NrBFIbYhBotKDvUoddd3M=,tag:jHxm9caNjL5zVSo55rLlUw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
