apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink
  namespace: shlink
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink
  template:
    metadata:
      labels:
        app: shlink
    spec:
      containers:
        - name: shlink
          image: shlinkio/shlink:stable
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: shlink-config
            - secretRef:
                name: shlink-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shlink
  namespace: shlink
spec:
  selector:
    app: shlink
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
