apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: points
data:
    .dockerconfigjson: ENC[AES256_GCM,data:6g8X5l0qYLeMprw/h6YYAOihe1Xbqhc0WPVaG5fXRLIqh0Et1KjqbIuZj4bs5mDDc3RgFaKxST0=,iv:/isyySP4KlLchg50zKNsPbrURFPHHne51j/iDVtPW/o=,tag:/e4lyypic9skg5xCUaRN1g==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RVd3d0FGRWlYQXN5ZlJM
            RXJNRkgvWXJzQ2xaQlhJZU5NRUxkczBNUjNzCnZxQmg0T2pUTEhlTmxKZFZnalM0
            aitkYnRzSUFyNXRBTzQzMFhWSXRaYkkKLS0tICs2T3FkaWxDWURiVEtRNE4rNHY5
            ekd5d3h2V244REJnWFhhdWN1Yk8xdWMK+R8Kgvj8bkpk9wILZ8zb7IdzRIGhsA/x
            n32xzb5wihYbiMA8jQKTc9OQHLlCOJ9yAowweVObakCVYR+mJsWYKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T17:24:03Z"
    mac: ENC[AES256_GCM,data:jqlxDXQtpGutXgmA10HzoEWDacqAt1EwDWwDrl9bKzVV+s5run9JPM80PKMLxpR6dFkdcgKnu3loYJHblVcJFhDfK/P7yIzt5nVc74lqjP+V6o3a2zWE7G7hdHcc38pu/OP3BASRXfRzIVQs1vMBS2ZgiA5HZmCjPJH6teTSonw=,iv:/emJttPONJAjb8RSbEFm1BLEEFqV068DaVkYhlX7USE=,tag:i/HdKZuG3q544M3dMCAbwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4