apiVersion: v1
kind: Secret
metadata:
    name: points
    namespace: points
data:
    AUTH_USER: ENC[AES256_GCM,data:AKMxsU1rmbA=,iv:y+1ensLEu8yd3wSeGGem1CxeI51aFhpNXtDoXyys2qs=,tag:6uEoDteqtjG+d2Z3+NPAVQ==,type:str]
    AUTH_PASS: ENC[AES256_GCM,data:dQL16kn4tkIpARIju6+CemmtMdZfeEF+ykluvQ8E91Zw2EYdhdAV1BlJ0KdhBLeGVVGFVbPpTj7HmboPDzVgeO4uuaD/9zL6pBZbzwsLRWk/U0LkQ404YdPyXAZhc33E5MzwTo+GNDVhnzbT8RjpjgQ5/yB8WnlIXKAJIOVND3+uDlGQChIo1zX8ueXbtlB4pyhG3fJCS+vC5Bk5c3Wia24ryy0arpPqD+6M6r6/UCHojPHgMS27Q4hsgI4=,iv:tJ5T1VrQKdlGv/MSNULsNk1yMwQ07Qdlhbo0r02luMM=,tag:pXUzRmOyHxzM+0waDvTzOQ==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:u7dr4EJGzCqV26G1jmWxycRpk7zfPYyVmzF9XhL7QxctiU0lWNo3OovUkgqACIMR1MlSnX3DatMS3G2345Z2sePGgsqpRwEPAhizvJp+qJY=,iv:n+BKurXnOump+RMq9J/uf2OUhPeUV3UTGZgPISD0z5I=,tag:sUf75j+wTVc19cqiAPs/Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fklxkacc5zep443xxjj8tm4t3zquzuahp2sen8v0f2j24ur83v3qazet3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNGJ4VHNGSTQvSU5NVzdi
            ZE1TQjB2clNNcmowMUtJaURnN2YzZjJPbFhBCmdDdU16SG51a3ptRFRXMGVBaXNx
            c2EvOUcvN0hkRFM5ZUdpSGlIMXZYZG8KLS0tIE9lcytGOFRRZlpub2JHZDFlU3Zx
            ekUvOWV4K013QlM3d1BlUnFxUCtucTQKNhPRFhYBM+XtXhZW6O1AnLXVio6mVOcG
            VX0t//gNKsHFE7S4EzTbPTZxakzzhMVuDDWXCHRPR1LQEbDYqWcY5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T18:18:10Z"
    mac: ENC[AES256_GCM,data:DXYDidAT7XvhJgaL8nRE9Z5weeJ4tN8bnFa013tj0Im9u222cUNbrAH8z8Ie2BoTet7fIr4E/RxjwFsVsWEwlswSmCSCe2YkSDrEQAOiwZelIzAe407X7/u6c6OQQAG9F027P8ptNuypPasTx+18bqvRYksx6LHUVEtDRUUYQcE=,iv:e3GhMLvfElS7amJAc14ax2iXtux5KrtRciLD6qSLWdU=,tag:zsMoF+qJToOHa/6lp2fFVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4