apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: "5.4.0"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: open-webui
  values:
    ollama:
      enabled: false
    extraEnvVars:
      - name: "OLLAMA_API_BASE_URL"
        value: "http://ollama.ollama.svc.cluster.local:11434"