apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: "12.1.0"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: open-webui
  values:
    ollama.models:
      - llama2
      - mistral
      - deepseek-r1
