apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 5m
  chart:
    spec:
      chart: stirling-pdf
      version: "2.2.0"
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: stirling-pdf
  values:
    ingress:
      enabled: true
      hosts:
        - host: stirlingpdf.bacherik.de
          path: /
          tls: true
          tlsSecretName: stirling-pdf-tls
      ingressClassName: traefik
    annotations:
      - cert-manager.io/cluster-issuer: "letsencrypt"
