apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 1h
  url: https://stirling-tools.github.io/Stirling-PDF-chart
