apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 5m
  chart:
    spec:
      chart: stirling-pdf-chart
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: stirling-pdf
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      tls: true
      tlsSecret: pdf-tls
      hosts:
        - pdf.bacherik.de